### PR TITLE
remove the dependency on the servlet api since it isn't required to buil...

### PR DESCRIPTION
**Pull request by benkiefer**
remove the dependency on the servlet api and introduce support for patch

### CODE REVIEW

**Comment by fabiomaffioletti** [comment]
Hello Ben, thank you for this. I'll take your modification about the servlet api, but not the patch verb one because it's not managed in the ui. Please also consider reading the contribution guidelines the next time so it will make my job easier.

**Comment by benkiefer** [comment]
Thank you sir. What are your plans for patch support? We need it soon, and would be happy to put together a pull request for the issue. Suggestions or concerns? @toranb and I will do a better job of following your guidelines next time.

**Comment by benkiefer** [comment]
I'm going to start by opening a new ticket for this and we can discuss it there. Thanks!

**Comment by toranb** [comment]
As @benkiefer suggested - we plan to open another ticket specific to the PATCH support! thanks again!

**Pull request closed without merging**
